version: "2"
services:
  tmpnginx:
    build: nginx
    restart: always
    ports:
      - "8030:80"
    networks:
      - core-network

  tmpmysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - core-network

networks:
  core-network:
    driver: bridge