version: "2"
services:
  web:
    image: nginx
    container_name: web
    restart: always
#    build:
#      context: .
#      dockerfile: ./nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ~/docker/nginx/html:/usr/share/nginx/html
      - ~/docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ~/docker/nginx/conf/conf.d:/etc/nginx/conf.d
    networks:
      - core-network

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - ~/docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - core-network

  gogs:
    image: gogs/gogs
    container_name: gogs
    restart: always
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - ~/docker/gogs:/data
    networks:
      - core-network

networks:
  core-network:
    driver: bridge