version: "2"
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - core-network

  mysql:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - core-network

  gogs:
    image: gogs/gogs
    restart: always
    ports:
      - "10022:22"
      - "10080:3000"
    networks:
      - core-network

networks:
  core-network:
    driver: bridge